# Generated by Django 4.1 on 2022-09-05 07:31

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('home', '0004_likepost'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='LikePost',
            new_name='Like',
        ),
    ]
